name: Build APK Manually (Corrected Dependencies)

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up a stable Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Install CORRECTED Buildozer dependencies for modern Ubuntu
      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev

      # Step 4: Manually install Buildozer
      - name: Install Buildozer
        run: pip install buildozer

      # Step 5: Run the Buildozer command
      - name: Run Buildozer
        run: buildozer android debug

      # Step 6: Upload the finished APK
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk