name: Build Android APK with Buildozer

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Buildozer
        id: buildozer
        uses: AndreMiras/actions-buildozer@v4.4.0
        with:
          command: buildozer android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.apk_file }}